Repository FightPandemics/FightPandemics, pull requests merged in 2020-12, with the labels that each got.

#1957 changed the edit and delete button to ellipsis
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/StyledComment.js
Labels: FRONTEND, High Priority, P3, UI Improvement, p_HelpBoard

#2013 #2012 - Fix 404 page when going to org profile on mobile
  client/src/components/DrawerMenu/ProfileMenu.js
Labels: bug

#2016 N/A - Fix black text on home page, for some languages
  client/src/components/Typography/TextLabel.js
  client/src/pages/Home.js
Labels: p_UI/UX Feedback

#2015 #2014 - various GTM fixes
  client/src/components/Feed/MessagesModal/MessageModal.js
  client/src/components/Feed/Post.js
  client/src/components/Inbox/InputBox.js
Labels: BI

#2000 Feature/post moderation without dashboard
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/reports.js
  backend/lib/endpoints/schema/reports.js
  backend/lib/index.js
  backend/lib/models/IndividualUser.js
  backend/lib/models/Post.js
  backend/lib/models/User.js
  client/src/assets/icons/edit-grey.svg
  client/src/assets/icons/eye-hide.svg
  client/src/assets/icons/follow.svg
  client/src/assets/icons/hide.svg
  client/src/assets/icons/moderator-badge.svg
  client/src/assets/icons/post-approval.svg
  client/src/assets/icons/post-removal.svg
  client/src/assets/icons/report.svg
  client/src/assets/icons/save.svg
  client/src/components/Button/SubMenuButton.js
  client/src/components/CreatePost/PostAs.js
  client/src/components/CreateReport/Body.js
  client/src/components/CreateReport/CreateReport.js
  client/src/components/CreateReport/Form.js
  client/src/components/CreateReport/Options.js
  client/src/components/CreateReport/ReportFinished.js
  client/src/components/CreateReport/SubTitle.js
  client/src/components/Feed/MessagesModal/MessageModal.js
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostCard.js
  client/src/components/Feed/PostDeleteModal.js
  client/src/components/Feed/PostDropdownButton.js
  client/src/components/Feed/PostPlaceHolder.js
  client/src/components/Feed/Posts.js
  client/src/components/Feed/StyledCommentButton.js
  client/src/components/Feed/StyledPostPage.js
  client/src/components/Feed/utils.js
  client/src/components/Header/Header.js
  client/src/components/Header/SettingMenu.js
  client/src/components/Header/StyledMenu.js
  client/src/components/Profile/Activity.js
  client/src/constants/gtm-tags.js
  client/src/hooks/actions/postActions.js
  client/src/hooks/reducers/postReducers.js
  client/src/locales/languages.js
  client/src/locales/translations/en_GB.json
  client/src/locales/translations/en_US.json
  client/src/reducers/posts/actions.js
  client/src/reducers/posts/reducer.js
  client/src/routes.js
  client/src/templates/RouteWithSubRoutes.js
Labels: MVP - Critical, f_postmoderation

#2039 AboutUs page - Add IDs for e2e tests
  client/src/pages/AboutUs.js
Labels: e2eTests

#2043 AboutUs page - Add IDs for e2e tests
  client/src/pages/AboutUs.js
Labels: e2eTests

#2041 #1987/#2017 - always use commentsCount inside post object
  backend/lib/endpoints/posts.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostSocial.js
  client/src/components/Feed/Posts.js
  client/src/components/Profile/Activity.js
  client/src/hooks/actions/postActions.js
  client/src/hooks/reducers/postReducers.js
  client/src/pages/PostPage.js
Labels: bug

#2027 Wrote additional tests for the About Us page Press section
  cypresse2e/cypress/elements/pages/aboutUs.js
  cypresse2e/cypress/fixtures/socialContactInfo.json
  cypresse2e/cypress/integration/e2eTests/aboutUs/aboutUs.spec.js
  cypresse2e/cypress/support/commands.js
Labels: e2eTests

#2036 Wrote additional tests for new languages on header section
  cypresse2e/cypress/integration/e2eTests/header/header.spec.js
Labels: e2eTests

#2026 Feature/api organisations
  mocha/test/organisation.test.js
  mocha/utils/apiEndpoints.js
  mocha/utils/apiHelper.js
  mocha/utils/validators.js
Labels: API Integration

#2067 Backend Test for GET api/posts Endpoint
  mocha/test/posts.test.js
  mocha/utils/apiEndpoints.js
  mocha/utils/validators.js
Labels: e2eTests

#2056 Feature/cypress remove memory errors
  cypresse2e/Dockerfile
  cypresse2e/cypress.json
  cypresse2e/cypress/elements/pages/helpBoard.js
  cypresse2e/cypress/elements/pages/homePage.js
  cypresse2e/cypress/elements/pages/offerHelpQuestionPage.js
  cypresse2e/cypress/integration/e2eTests/home/homePage.spec.js
  cypresse2e/cypress/integration/e2eTests/offerHelp/offerHelpQuestion.spec.js
  cypresse2e/cypress/integration/e2eTests/post/post.spec.js
  cypresse2e/package-lock.json
  cypresse2e/package.json
  docker-compose.yml
Labels: e2eTests

#1727 #781 - accounts linking
  backend/lib/components/Auth0.js
  backend/lib/endpoints/auth.js
  client/src/locales/translations/en_US.json
  client/src/pages/CreateUserProfile.js
Labels: p_Profile/Account

#2092 #2086 - mobile GTM fixes
  client/src/components/DrawerMenu/LanguageMenu.js
  client/src/components/DrawerMenu/components.js
  client/src/components/Feed/CreatePostButton.js
  client/src/components/Inbox/Messages.js
  client/src/constants/gtm-tags.js
  client/src/pages/Feed.js
Labels: BI

#2095 Fixed FAQ page in Kannada language (which displayed blank page) - Issue #2073
  client/src/locales/translations/kn_IN.json
Labels: Difficulty - Easy, FRONTEND

#2053 Disable location sorting by default, add toggle to enable it
  backend/lib/endpoints/organisations.js
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/schema/organisations.js
  backend/lib/endpoints/schema/users.js
  backend/lib/endpoints/users.js
  backend/lib/models/Post.js
  backend/lib/models/User.js
  client/src/components/Feed/FeedWrappers.js
  client/src/components/Feed/FilterAccordion.js
  client/src/components/Feed/StyledAccordion.js
  client/src/locales/translations/en_US.json
  client/src/pages/Feed.js
Labels: p_HelpBoard
