Repository FightPandemics/FightPandemics, pull requests merged in 2020-05, with the labels that each got.

#224 Feature/#210 fastify sensible
  README.md
  backend/lib/endpoints/auth.js
  backend/lib/endpoints/users.js
  backend/lib/index.js
  backend/package-lock.json
  backend/package.json
Labels: BACKEND, documentation, enhancement

#191 Update Post data model
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/schema/posts.js
  backend/lib/models/index.js
  backend/lib/models/schemas/User.js
  backend/lib/models/schemas/v1/Post.js
  backend/lib/models/schemas/v2/author.js
  backend/lib/models/schemas/v2/post.js
  backend/package-lock.json
  backend/package.json
Labels: BACKEND, Post

#286 fix typo
  README.md
Labels: documentation

#318 fix link on PR template
  .github/pull_request_template.md
Labels: documentation

#291 [174] Feed page styling desktop
  client/src/assets/data/fakePosts.js
  client/src/assets/icons/back.svg
  client/src/assets/icons/filters.svg
  client/src/assets/icons/submenu.svg
  client/src/components/Feed/FeedWrapper.js
  client/src/components/Feed/FilterAccordion.js
  client/src/components/Feed/FilterBox.js
  client/src/components/Feed/FiltersList.js
  client/src/components/Feed/FiltersSidebar.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostCard.js
  client/src/components/Feed/PostSocial.js
  client/src/components/Navigation/DesktopNavbar.js
  client/src/components/Tag/ButtonTag.js
  client/src/constants/colors.js
  client/src/hooks/actions/feedActions.js
  client/src/hooks/reducers/feedReducers.js
  client/src/pages/Feed.js
  client/src/templates/layouts/LogoLayout.js
  client/src/templates/layouts/NavigationLayout.js
Labels: FRONTEND

#331 submit button will redirected to feed page
  client/src/pages/NeedHelp.js
Labels: FRONTEND, bug

#347 Feature/339/fix password mask
  client/src/assets/icons/eye-mask.svg
  client/src/assets/icons/eye-unmask.svg
  client/src/assets/icons/eye.svg
  client/src/constants/theme.js
  client/src/pages/Login.js
Labels: FRONTEND, Login, bug

#362 fixed incorrect numbering on symptom checker
  client/src/pages/OfferHelp.js
  client/src/pages/SymptomsCheck.js
Labels: FRONTEND, bug

#284 Data model migration v2
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/schema/posts.js
  backend/lib/models/Comment.js
  backend/lib/models/Feedback.js
  backend/lib/models/Location.js
  backend/lib/models/Organization.js
  backend/lib/models/Post.js
  backend/lib/models/User.js
  backend/lib/models/author.js
  backend/lib/plugins/mongoose-connector.js
  backend/package-lock.json
  backend/package.json
Labels: BACKEND, Post, Post Filters

#377 Add automatic index syncing between model and db
  backend/lib/plugins/mongoose-connector.js
Labels: BACKEND, Database

#380 [179] Add api calls to feed page.
  client/src/components/Feed/Post.js
  client/src/components/TextAvatar/index.js
  client/src/hooks/actions/feedActions.js
  client/src/hooks/reducers/feedReducers.js
  client/src/pages/Feed.js
Labels: FRONTEND

#379 Adjust post endpoints to reflect changes at user model
  backend/lib/endpoints/posts.js
Labels: BACKEND, Post

#396 Fixed the numbering order for issue 356
  client/src/pages/SymptomsCheck.js
Labels: FRONTEND

#404 Fix case of setting post expiration with 'forever' option
  backend/lib/endpoints/posts.js
Labels: BACKEND, Post, bug

#403 Add state and zip to location model
  backend/lib/models/Location.js
Labels: BACKEND, Database, geolocation

#397 Fixed unselect/select options
  client/src/pages/SymptomsCheck.js
Labels: FRONTEND, bug

#386 Separate Auth0 tenants for each environment
  .github/workflows/review-delete-workflow.yml
  .github/workflows/review-workflow.yml
  .github/workflows/staging-workflow.yml
  main.tf
Labels: DevOps

#407 Feature/[406]Changed default text from in my zip code to in my city
  client/src/assets/data/createPostSettings.js
Labels: FRONTEND, Frontend clean up

#414 trim Posts.externalLinks items
  backend/lib/models/Post.js
Labels: Database, Post

#400 Feature/#165 sc page change
  client/src/assets/icons/disclaimer.svg
  client/src/components/NearestHospital/LocalEmergencyNumber.js
  client/src/components/StepWizard/WizardNav.js
  client/src/components/StepWizard/WizardStep.js
  client/src/components/Typography/Heading.js
  client/src/pages/CovidScreening/GenericMessage.js
  client/src/pages/CovidScreening/Under18.js
  client/src/pages/ResultsPage.js
  client/src/pages/SymptomsCheck.js
  client/src/templates/layouts/MobileTabs.js
Labels: FRONTEND

#429 fix title
  client/public/index.html
Labels: FRONTEND

#373 Add options for unauthenticated user at /posts
  backend/lib/endpoints/posts.js
Labels: BACKEND, Post

#299 Footnote
  client/src/components/Feed/Post.js
  client/src/components/Footnote.js
  client/src/components/Header.js
  client/src/components/NearestHospital/LocalEmergencyNumber.js
  client/src/constants/theme.js
  client/src/hooks/reducers/feedReducers.js
  client/src/routes.js
  client/src/templates/RouteWithSubRoutes.js
  client/src/templates/layouts/Main.js
  client/src/templates/layouts/NavigationLayout.js
Labels: help wanted

#424 Add support for Cypress framework and first e2e test using Cypress - Feature/cypresse2e
  .gitignore
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/e2eTests/homePage.js
  cypress/integration/e2eTests/homePage.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
Labels: e2eTests

#460 Add Sentry error notifier
  .github/workflows/review-workflow.yml
  .github/workflows/staging-workflow.yml
  backend/config.js
  backend/lib/index.js
  backend/lib/plugins/error-handler.js
  backend/package-lock.json
  backend/package.json
  main.tf
Labels: BACKEND, DevOps

#475 Bugfix: error handler - pass proper error object to Sentry
  backend/lib/plugins/error-handler.js
Labels: BACKEND

#491 fixed spelling mistakes on feed page and filter side page.
  client/src/assets/data/filterOptions.js
  client/src/components/Feed/FiltersSidebar.js
  client/src/pages/Feed.js
Labels: FRONTEND, Frontend clean up

#445 Add photo and liked to /posts endpoint and update userId usage count
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/schema/posts.js
  backend/lib/models/Author.js
  backend/lib/models/User.js
Labels: BACKEND, Database, Post

#499 changed the text from whom to providers
  client/src/assets/data/filterOptions.js
Labels: FRONTEND, Frontend clean up

#489 Feature/missing envelop icon 432
  client/src/assets/icons/envelope.svg
  client/src/components/Header.js
Labels: FRONTEND

#401 Data model/users v2
  backend/lib/endpoints/organizations.js
  backend/lib/endpoints/schema/location.js
  backend/lib/endpoints/schema/organizations.js
  backend/lib/endpoints/schema/users.js
  backend/lib/endpoints/users.js
  backend/lib/models/Comment.js
  backend/lib/models/IndividualUser.js
  backend/lib/models/Location.js
  backend/lib/models/Organization.js
  backend/lib/models/OrganizationUser.js
  backend/lib/models/Post.js
  backend/lib/models/User.js
  backend/lib/plugins/mongoose-connector.js
  backend/lib/utils.js
Labels: BACKEND, Database, Difficulty - Hard

#402 [180] Post like behavior.
  client/src/actions/authActions.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostSocial.js
  client/src/components/Feed/Posts.js
  client/src/hooks/actions/feedActions.js
  client/src/hooks/reducers/feedReducers.js
  client/src/pages/Feed.js
  client/src/pages/Login.js
  client/src/templates/RouteWithSubRoutes.js
  client/src/utils/auth-token.js
Labels: FRONTEND

#425 Update Create Post flow design on Desktop to Match Figma
  .gitignore
  client/src/GlobalStyles.js
  client/src/assets/icons/down-arrow-slim.svg
  client/src/components/CreatePost/CreatePost.js
  client/src/components/CreatePost/Form/AskHelp.js
  client/src/components/CreatePost/Form/FirstSection.js
  client/src/components/CreatePost/Form/Form.js
  client/src/components/CreatePost/Form/Head.js
  client/src/components/CreatePost/Form/OfferHelp.js
  client/src/components/CreatePost/Form/SecondSection.js
  client/src/components/CreatePost/Form/ThirdSection.js
  client/src/components/CreatePost/PostAs.js
  client/src/components/CreatePost/StyledModal.js
  client/src/components/CreatePost/StyledPostAs.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostSocial.js
  client/src/components/Header.js
  client/src/components/PostAs/PostAs.js
  client/src/components/Selector/Selector.js
  client/src/components/Selector/StyledSelector.js
  client/src/components/Tag/AddTags.js
  client/src/components/Tag/ButtonTag.js
  client/src/hooks/reducers/feedReducers.js
  client/src/index.js
  client/src/pages/Feed.js
  client/src/pages/Login.js
  client/src/pages/Profile.js
  client/src/routes.js
  client/src/utils/auth-token.js
Labels: FRONTEND

#522 doc that feature/ branches should be in the main repo
  README.md
Labels: documentation

#504 Add pagination to /posts endpoint
  backend/lib/endpoints/posts.js
Labels: BACKEND, Post

#518 Create confirmation modal to post
  client/src/components/CreatePost/CreatePost.js
  client/src/components/CreatePost/Form/Form.js
  client/src/components/CreatePost/StyledPostAs.js
Labels: FRONTEND

#472 [WIP] Auth0 - Set AUTH_APP_URL based on environment
  main.tf
Labels: DevOps
