Repository FightPandemics/FightPandemics, pull requests merged in 2020-08, with the labels that each got.

#1312 Fix Terraform deprecated host_header condition syntax
  terraform-task-module/alb-listener-rule.tf
Labels: DevOps

#1313 Add support for development AWS environment
  deploy-development.sh
  main.tf
Labels: DevOps

#1336 fixed need/offer help spacing
  client/src/components/StepWizard/StyledDiv.js
  client/src/components/StepWizard/WizardSubmit.js
Labels: FRONTEND

#1328 Removed unused Org Complete file and refactored ProfileCompleted.js per user path
  client/src/pages/Feed.js
  client/src/pages/OrgProfileComplete.js
  client/src/pages/PostPage.js
  client/src/pages/ProfileCompleted.js
  client/src/routes.js
Labels: Frontend clean up

#1319 Refactor tests to use pom and add Readme file
  cypresse2e/Readme.md
  cypresse2e/cypress/elements/pages/Header.js
  cypresse2e/cypress/elements/pages/HomePage.js
  cypresse2e/cypress/integration/e2eTests/header/header.spec.js
  cypresse2e/cypress/integration/e2eTests/home/homePage.spec.js
Labels: e2eTests

#1357 Test POM files -change files name to lowercase
  cypresse2e/cypress/elements/pages/header.js
  cypresse2e/cypress/elements/pages/homePage.js
Labels: e2eTests

#1358 Removed extra files from cypress service
  cypresse2e/cypress/elements/pages/Header.js
  cypresse2e/cypress/elements/pages/HomePage.js
Labels: Frontend clean up

#1360 More Human Readable Backend Logs
  backend/lib/index.js
  backend/package-lock.json
  backend/package.json
Labels: BACKEND

#1354 Automated test on sign up page using POM
  cypresse2e/Readme.md
  cypresse2e/cypress.json
  cypresse2e/cypress/elements/pages/joinNow.js
  cypresse2e/cypress/integration/e2eTests/joinNow/joinNow.spec.js
Labels: e2eTests

#1334 Error success message for org email update
  backend/lib/endpoints/organisations.js
  client/src/components/Alert/SuccessAlert.js
  client/src/pages/EditOrganisationAccount.js
Labels: FRONTEND, Organisation Edit

#1380 Pin Terraform versions
  .github/workflows/production-workflow.yml
  .github/workflows/review-delete-workflow.yml
  .github/workflows/review-workflow.yml
  .github/workflows/staging-workflow.yml
Labels: DevOps

#1383 Feature/cypress tests for footer section and sign in page
  cypresse2e/cypress/elements/pages/footer.js
  cypresse2e/cypress/elements/pages/signIn.js
  cypresse2e/cypress/integration/constants.js
  cypresse2e/cypress/integration/e2eTests/footer/footer.spec.js
  cypresse2e/cypress/integration/e2eTests/signIn/signIn.spec.js
Labels: e2eTests

#1382 Feature/cookie banner test
  client/src/components/CookieAlert.js
  cypresse2e/cypress/elements/pages/homePage.js
  cypresse2e/cypress/integration/e2eTests/home/homePage.spec.js
Labels: HomePage, e2eTests

#1418 Fix revival of review build
  .github/workflows/review-workflow.yml
  README.md
Labels: DevOps

#1423 Recover password screen e2e tests
  cypresse2e/cypress/elements/pages/recoverPassword.js
  cypresse2e/cypress/integration/constants.js
  cypresse2e/cypress/integration/e2eTests/recoverPassword/recoverPassword.spec.js
  cypresse2e/cypress/support/commands.js
Labels: e2eTests

#1456 Add port to the mongo service - docker-compose
  docker-compose.yml
Labels: BACKEND
