Repository FightPandemics/FightPandemics, pull requests merged in 2020-11, with the labels that each got.

#1720 #1426 Notifications Lambda
  .github/workflows/production-notification-service.yml
  .github/workflows/review-notification-service.yml
  .github/workflows/staging-notification-service.yml
  services/notification/.editorconfig
  services/notification/deploy/cloudwatch.tf
  services/notification/deploy/lambda.tf
  services/notification/deploy/role.tf
  services/notification/deploy/variables.tf
  services/notification/src/config.js
  services/notification/src/helpers/database-helper.js
  services/notification/src/helpers/date-helper.js
  services/notification/src/helpers/error-notifier.js
  services/notification/src/helpers/logger.js
  services/notification/src/helpers/mailer.js
  services/notification/src/helpers/template-builder.js
  services/notification/src/lambda.js
  services/notification/src/local.js
  services/notification/src/models/share-medium.js
  services/notification/src/package-lock.json
  services/notification/src/package.json
  services/notification/src/service.js
  services/notification/src/templates/base.html
  services/notification/src/templates/base.txt
  services/notification/src/templates/instant/comment.html
  services/notification/src/templates/instant/comment.txt
  services/notification/src/templates/instant/like.html
  services/notification/src/templates/instant/like.txt
  services/notification/src/templates/instant/share.html
  services/notification/src/templates/instant/share.txt
  services/notification/src/tests/test-database-helper.js
  services/notification/src/tests/test-notification.js
  services/notification/src/tests/test-template-builder.js
Labels: p_Notifications

#1746 Fix #1745 search box breaking to multiple lines
  client/src/components/Input/FeedSearch.js
  client/src/components/Input/SearchCategories.js
  client/src/pages/Feed.js
Labels: FRONTEND, p_searchkeyword

#1758 Fix Visibility drop-down not visible on requesting help tab
  client/src/components/Selector/Selector.js
Labels: FRONTEND, bug

#1711 Add Mochawesome Report Generator for Cypress Tests
  client/src/components/Tag/ButtonTag.js
  client/src/locales/translations/en_GB.json
  client/src/locales/translations/pl.json
  cypresse2e/.gitignore
  cypresse2e/Readme.md
  cypresse2e/cypress.json
  cypresse2e/cypress/integration/e2eTests/offerHelp/offerHelpQuestion.spec.js
  cypresse2e/cypress/integration/e2eTests/requestHelp/requestHelpQuestion.spec.js
  cypresse2e/package-lock.json
  cypresse2e/package.json
  docker-compose.yml
Labels: e2eTests

#1762 Cypress add logs for failed tests
  cypresse2e/.gitignore
  cypresse2e/cypress/plugins/index.js
  cypresse2e/cypress/support/index.js
  cypresse2e/package-lock.json
  cypresse2e/package.json
Labels: e2eTests

#1747 Feature/1740 notif
  backend/lib/endpoints/posts.js
  backend/lib/models/Notification.js
  backend/lib/plugins/notifier.js
  backend/lib/plugins/socket.js
  client/src/components/Notifications/NotificationDropDown.js
  client/src/context/WebsocketContext.js
  client/src/locales/translations/en_US.json
  client/src/pages/Unsubscribe.js
Labels: p_Notifications

#1771 Notifications - deduplicate likes on a single post by the same user
  backend/lib/models/Notification.js
  backend/lib/plugins/notifier.js
Labels: p_Notifications

#1764 validations for forgot password
  cypresse2e/cypress/integration/e2eTests/forgotPassword/forgotPassword.spec.js
Labels: e2eTests

#1683 Fixed the Linkedin url validation in edit profile
  client/src/pages/EditProfile.js
Labels: bug

#1728 Use query strings for filters/search
  client/package.json
  client/src/components/Feed/FeedWrapper.js
  client/src/components/Feed/FeedWrappers.js
  client/src/components/Feed/FilterAccordion.js
  client/src/components/Feed/FilterBox.js
  client/src/components/Feed/FiltersList.js
  client/src/components/Feed/utils.js
  client/src/components/Header.js
  client/src/components/Input/FeedSearch.js
  client/src/components/Input/SearchCategories.js
  client/src/hooks/actions/feedActions.js
  client/src/hooks/reducers/feedReducers.js
  client/src/pages/Feed.js
  client/src/pages/NeedHelp.js
  client/src/pages/OfferHelp.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/Profile.js
  client/src/templates/layouts/NavigationLayout.js
Labels: FRONTEND, Post Filters, p_HelpBoard, p_searchkeyword

#1653 Fixed the Like feature user lose track of the post
  client/src/components/Feed/PostSocial.js
Labels: bug

#1803 notifications dropdown UI improvements
  client/src/components/Notifications/NotificationDropDown.js
Labels: UI, f_notification, p_Notifications

#1769 Backend Test for Feedback Endpoint & Update Login Endpoint Error Messages
  mocha/test/feedback.test.js
  mocha/test/login.test.js
  mocha/utils/apiEndpoints.js
  mocha/utils/testData.js
  mocha/utils/validators.js
Labels: e2eTests

#1802 Correct Test for German language - Header
  cypresse2e/cypress/integration/e2eTests/header/header.spec.js
Labels: e2eTests

#1817 Translation: Add 7 new languages
  client/src/constants/gtm-tags.js
  client/src/locales/index.js
  client/src/locales/languages.js
  client/src/locales/translations/fr.json
  client/src/locales/translations/kn_IN.json
  client/src/locales/translations/ms_MY.json
  client/src/locales/translations/te_IN.json
  client/src/locales/translations/tr.json
  client/src/locales/translations/vi.json
  client/src/locales/translations/zh_CN.json
Labels: p_Internationalisation/Localisation

#1819 fix 1818, no translation key for GetInvolved Dialog
  client/src/components/Button/GetInvolvedButton.js
  client/src/locales/translations/en_US.json
  client/src/pages/AboutUs.js
Labels: p_Internationalisation/Localisation

#1783 fix: back to create post
  client/src/pages/Feed.js
  client/src/templates/RouteWithSubRoutes.js
Labels: FRONTEND

#1822 #1741 update message thread schemas
  backend/lib/models/Message.js
  backend/lib/models/Thread.js
  backend/lib/plugins/socket.js
Labels: p_Notifications

#1775 782 - Logout user from all tabs
  client/src/actions/authActions.js
  client/src/reducers/sessionReducer.js
Labels: FRONTEND

#1825 Web notifications date i18n
  client/src/components/Notifications/NotificationDropDown.js
Labels: f_notification, p_Notifications

#1821 #1741 Email notifications for DMs
  services/notification/deploy/cloudwatch.tf
  services/notification/src/helpers/database-helper.js
  services/notification/src/helpers/template-builder.js
  services/notification/src/local.js
  services/notification/src/models/email-frequency.js
  services/notification/src/models/message-thread-status.js
  services/notification/src/service.js
  services/notification/src/templates/instant/message-request.html
  services/notification/src/templates/instant/message-request.txt
  services/notification/src/templates/instant/message.html
  services/notification/src/templates/instant/message.txt
Labels: p_Notifications

#1823 Fix notification digest email styling
  services/notification/src/templates/base.html
  services/notification/src/templates/digests/_post.html
Labels: p_Notifications

#1830 Fix DM email notifications
  services/notification/src/helpers/database-helper.js
Labels: p_Notifications

#1687 #1339 - Password Change Screen
  .gitignore
  backend/lib/components/Auth0.js
  backend/lib/endpoints/auth.js
  backend/lib/endpoints/schema/auth.js
  backend/lib/endpoints/users.js
  backend/lib/models/IndividualUser.js
  client/src/components/EditProfile/EditComponents.js
  client/src/components/Input/InputError.js
  client/src/components/Profile/ProfileComponents.js
  client/src/locales/translations/en_US.json
  client/src/pages/EditAccount.js
  client/src/pages/EditProfile.js
  client/src/pages/EditSecurity.js
  client/src/pages/Login.js
  client/src/pages/Profile.js
  client/src/routes.js
  client/src/templates/RouteWithSubRoutes.js
Labels: FRONTEND

#1846 Lokalise: Translations update
  client/src/locales/translations/en_GB.json
  client/src/locales/translations/en_US.json
  client/src/locales/translations/fr.json
  client/src/locales/translations/pl.json
Labels: p_Internationalisation/Localisation

#1856 Improvements: switch account menu, and confirm popup
  client/src/GlobalStyles.js
  client/src/components/DrawerMenu/DrawerMenu.js
  client/src/components/Header/Header.js
  client/src/components/Header/LanguageMenu.js
  client/src/components/Header/StyledMenu.js
  client/src/components/Profile/ProfileComponents.js
  client/src/components/WithSummitBanner.js
  client/src/locales/translations/en_US.json
  client/src/pages/AboutUs.js
  client/src/pages/Logout.js
  client/src/templates/RouteWithSubRoutes.js
  client/src/templates/layouts/NavigationLayout.js
Labels: FRONTEND, UI Improvement

#1859 Lokalise: Translations update
  client/src/locales/translations/en_GB.json
  client/src/locales/translations/en_US.json
  client/src/locales/translations/fr.json
  client/src/locales/translations/pl.json
Labels: p_Internationalisation/Localisation

#1810 Feature/privacy policy-Add validation tests for privacy policy page
  cypresse2e/cypress/elements/pages/privacyPolicy.js
  cypresse2e/cypress/fixtures/privacyPolicyContent.json
  cypresse2e/cypress/integration/e2eTests/privacyPolicy/privacyPolicy.spec.js
Labels: e2eTests

#1870 ORG switch GTM tag update: Add the account type to the data layer
  client/src/actions/authActions.js
Labels: BI

#1877 Notifications merged with STG
  backend/config.js
  backend/lib/index.js
  backend/lib/plugins/socket.js
  client/public/index.html
  client/src/components/Feed/NestedComments.js
  cypresse2e/cypress/elements/pages/privacyPolicy.js
  cypresse2e/cypress/fixtures/privacyPolicyContent.json
  cypresse2e/cypress/integration/e2eTests/privacyPolicy/privacyPolicy.spec.js
  terraform-task-module/alb-listener-rule.tf
  terraform-task-module/service.tf
Labels: f_notification, p_Notifications

#1866 Feature/1843 org vs individual edit delete post
  client/src/components/CreatePost/CreatePost.js
  client/src/components/CreatePost/Form/Form.js
  client/src/components/CreatePost/StyledPostAs.js
  client/src/components/Feed/Post.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/PostPage.js
  client/src/pages/Profile.js
Labels: Organisation Edit

#1886 #1876 Notification emails: add link tracking
  services/notification/src/helpers/template-builder.js
  services/notification/src/models/email-frequency-tracking-code.js
  services/notification/src/templates/digests/_post.html
  services/notification/src/templates/instant/comment.html
  services/notification/src/templates/instant/like.html
  services/notification/src/templates/instant/message-request.html
  services/notification/src/templates/instant/message.html
  services/notification/src/templates/instant/share.html
  services/notification/src/tests/test-template-builder.js
Labels: f_notification, p_Notifications

#1888 Fix realtime notifications
  backend/lib/plugins/notifier.js
  backend/lib/plugins/socket.js
Labels: f_notification, p_Notifications

#1889 Fix tracking link in notification email for share
  services/notification/src/templates/instant/share.html
Labels: f_notification, p_Notifications

#1880 Messaging: UI Improvements
  backend/lib/endpoints/auth.js
  client/src/components/Feed/MessagesModal/MessageModal.js
  client/src/components/Feed/PostSocial.js
  client/src/components/Inbox/ChatList.js
  client/src/components/Inbox/Container.js
  client/src/components/Inbox/EmptyInbox.js
  client/src/components/Inbox/MessagesContainers.js
  client/src/components/Inbox/RecipientHeader.js
  client/src/components/Inbox/SelectRoom.js
  client/src/components/Inbox/Settings.js
  client/src/components/Inbox/SettingsHeader.js
  client/src/pages/Inbox.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/Profile.js
Labels: FRONTEND, p_Messaging

#1898 Lokalise: English Translations update (fixing some keys)
  client/src/locales/translations/en_US.json
Labels: p_Internationalisation/Localisation

#1812 Cypress e2e tests for the About Us page
  cypresse2e/cypress/elements/pages/aboutUs.js
  cypresse2e/cypress/fixtures/socialContactInfo.json
  cypresse2e/cypress/integration/e2eTests/aboutUs/aboutUs.spec.js
  cypresse2e/cypress/support/commands.js
Labels: e2eTests

#1912 translation: add 5 languages, and update older ones
  client/src/constants/gtm-tags.js
  client/src/locales/index.js
  client/src/locales/languages.js
  client/src/locales/translations/ar.json
  client/src/locales/translations/de.json
  client/src/locales/translations/en_GB.json
  client/src/locales/translations/fr.json
  client/src/locales/translations/it.json
  client/src/locales/translations/kn_IN.json
  client/src/locales/translations/mk_MK.json
  client/src/locales/translations/ms_MY.json
  client/src/locales/translations/pl.json
  client/src/locales/translations/pt_PT.json
  client/src/locales/translations/te_IN.json
  client/src/locales/translations/tl.json
  client/src/locales/translations/tr.json
  client/src/locales/translations/vi.json
  client/src/locales/translations/zh_CN.json
  client/src/locales/translations/zh_TW.json
Labels: p_Internationalisation/Localisation

#1913 #1894 - messaging popup issues fix
  backend/package-lock.json
  backend/package.json
  client/src/components/Feed/MessagesModal/MessagesContainer.js
  client/src/components/Feed/PostShare.js
  client/src/components/Feed/User.js
  client/src/pages/OrganisationProfile.js
Labels: p_Messaging

#1921 #1920 Tweak/fix digest emails
  services/notification/src/helpers/database-helper.js
  services/notification/src/helpers/template-builder.js
  services/notification/src/templates/digests/_post.html
  services/notification/src/templates/digests/_post.txt
Labels: p_Notifications

#1932 Fix delete post/comment modal UI
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostDeleteModal.js
  client/src/locales/translations/en_US.json
Labels: FRONTEND

#1956 #1948 - fix "view help board" button visibility
  client/src/pages/Home.js
  client/src/templates/layouts/Main.js
Labels: FRONTEND, p_UI/UX Feedback

#1935 added minWidth prop to StyledSelector to fix selector item text cutoff
  client/src/components/CreatePost/Form/ThirdSection.js
  client/src/components/Selector/Selector.js
  client/src/components/Selector/StyledSelector.js
Labels: FRONTEND, Frontend clean up

#1934 fix fonts for Vietnamese, (and other languages)
  client/src/components/CookieAlert.js
  client/src/components/Footnote.js
  client/src/constants/theme.js
  client/src/pages/VerifyEmail.js
Labels: FRONTEND

#1959 #1916 - added missing translation keys for messaging and notifications
  client/src/components/Feed/MessagesModal/MessageModal.js
  client/src/components/Inbox/OrgPost.js
  client/src/components/Input/NotifyPreferenceInput.js
  client/src/components/Notifications/NotificationDropDown.js
  client/src/locales/translations/en_US.json
Labels: p_Internationalisation/Localisation

#1864 Backend Test for Signup Endpoint - Negative Testing
  mocha/test/login.test.js
  mocha/test/signup.test.js
  mocha/utils/apiEndpoints.js
  mocha/utils/testData.js
Labels: e2eTests

#1970 Change spanish display name
  client/src/locales/index.js
  client/src/locales/languages.js
Labels: p_Internationalisation/Localisation

#1958 #1947- shift+enter for new line when creating comment
  client/src/components/Feed/Post.js
  client/src/components/Input/AutoSize.js
Labels: p_UI/UX Feedback

#1941 Updated Validation Message in Backend Test for Feedback Endpoint - Rating & Age
  mocha/test/feedback.test.js
Labels: e2eTests

#1980 Move the AccessiBe and Datadog logos to Lifetime supporters
  client/src/pages/AboutUs.js
Labels: p_About_US

#1976 #1931 - Modify labels on post cards
  client/src/components/Feed/Post.js
  client/src/components/Tag/PostTag.js
Labels: p_UI/UX Feedback

#1977 #1975 - Add new types of Help
  backend/lib/models/Post.js
  client/src/assets/data/filterOptions.js
  client/src/locales/translations/en_US.json
Labels: Post Filters

#1964 Added clear notifications feature and fixed mobile UI issues with notification dropdown
  backend/lib/models/Notification.js
  backend/lib/plugins/notifier.js
  backend/lib/plugins/socket.js
  client/src/actions/wsActions.js
  client/src/components/Notifications/NotificationDropDown.js
  client/src/context/WebsocketContext.js
  client/src/reducers/wsReducers.js
Labels: High Priority, p_Notifications

#1937 Correct test for Header.spec.js
  cypresse2e/cypress/integration/e2eTests/header/header.spec.js
Labels: e2eTests

#1979 messaging: GTM, improvements, and bug fixes
  backend/lib/plugins/socket.js
  backend/lib/utils.js
  client/src/components/Header/Header.js
  client/src/components/Inbox/InputBox.js
  client/src/components/Inbox/Messages.js
  client/src/context/WebsocketContext.js
Labels: p_Messaging

#1983 #1982 - Add request/offer label to post, UI and accessibility improvements
  client/src/GlobalStyles.js
  client/src/assets/icons/large-plus.svg
  client/src/assets/icons/pretty-plus.svg
  client/src/components/DrawerMenu/AccountMenu.js
  client/src/components/Feed/CreatePostButton.js
  client/src/components/Feed/FeedWrappers.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostCard.js
  client/src/components/Feed/Posts.js
  client/src/components/Header/AccountMenu.js
  client/src/components/Profile/ProfileComponents.js
  client/src/components/Tag/PostTag.js
  client/src/constants/colors.js
  client/src/constants/theme.js
  client/src/pages/Feed.js
  client/src/pages/Login.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/Profile.js
Labels: FRONTEND

#1996 Lokalise: Translations update
  client/src/locales/translations/ar.json
  client/src/locales/translations/de.json
  client/src/locales/translations/en_GB.json
  client/src/locales/translations/es_ES.json
  client/src/locales/translations/fr.json
  client/src/locales/translations/it.json
  client/src/locales/translations/kn_IN.json
  client/src/locales/translations/mk_MK.json
  client/src/locales/translations/ms_MY.json
  client/src/locales/translations/pl.json
  client/src/locales/translations/pt_PT.json
  client/src/locales/translations/ru.json
  client/src/locales/translations/te_IN.json
  client/src/locales/translations/tl.json
  client/src/locales/translations/tr.json
  client/src/locales/translations/vi.json
  client/src/locales/translations/zh_CN.json
  client/src/locales/translations/zh_TW.json
Labels: p_Internationalisation/Localisation

#1919 Use npm ci for reliable, repeatable builds
  backend/Dockerfile
  backend/Dockerfile.dev
  client/Dockerfile
  client/Dockerfile.dev
  client/package-lock.json
Labels: DevOps
