Repository FightPandemics/FightPandemics, pull requests merged in 2020-06, with the labels that each got.

#544 Send only 500 errors to Sentry
  backend/lib/plugins/error-handler.js
Labels: BACKEND

#536 [181] Create comment in a post.
  client/src/components/Feed/Comments.js
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/Post.js
  client/src/hooks/actions/feedActions.js
  client/src/hooks/reducers/feedReducers.js
  client/src/pages/Feed.js
Labels: FRONTEND

#511 Fixed search bar border and replaced navigation icon to match the style on figma
  client/src/assets/icons/navigation.svg
  client/src/assets/icons/search-blue.svg
  client/src/components/Card/DescriptionCard.js
  client/src/components/Feed/FiltersSidebar.js
  client/src/components/Input/LocationSearch.js
  client/src/pages/Login.js
Labels: FRONTEND, Frontend clean up

#556 [543] Small fix: Changes the default visibility of a post from 'Forever' to 'Month'
  client/src/assets/data/createPostSettings.js
Labels: MVP - Release 1

#549 [529] In the "Give Help" page, clicking divs with text options toggles the checkboxes
  .gitignore
  client/src/components/StepWizard/WizardCheckboxItem.js
  client/src/pages/OfferHelp.js
Labels: Desktop, FRONTEND, MVP - Release 1, Mobile Web, bug

#378 Data model/comments v2
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/schema/posts.js
  backend/lib/models/Comment.js
Labels: BACKEND, Comment

#560 [537] Email validation fix - validate email top-level domains on sign-up
  client/package.json
  client/src/utils/validators.js
Labels: Desktop, Mobile, bug

#584 Feature/submit size issue563
  client/src/components/StepWizard/WizardButtonGroup.js
  client/src/pages/OfferHelp.js
Labels: FRONTEND

#593 Fix AUTH_APP_URL
  main.tf
Labels: BACKEND

#596 added airtable api keys to /backend/.env.example_docker
  backend/.env.example_docker
Labels: BACKEND, bug

#587 Add Papertrail, and allow log level to be configurable
  backend/config.js
  backend/lib/index.js
  backend/lib/logger.js
  backend/package-lock.json
  backend/package.json
  main.tf
Labels: BACKEND

#612 [513] Clean up thrown and logged errors
  backend/lib/endpoints/auth.js
  backend/lib/endpoints/feedback.js
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/users.js
Labels: BACKEND, MVP - Release 1

#610 fixed email validation on offer help page
  client/src/pages/OfferHelp.js
Labels: FRONTEND

#669 Uncommented emergency num lines temp
  client/src/templates/layouts/MobileTabs.js
Labels: Frontend clean up

#670 Fix button size to to be center on desktop and mobile
  client/src/components/Button/FeedbackButton.js
  client/src/components/StepWizard/WizardSubmit.js
  client/src/pages/OfferHelp.js
Labels: FRONTEND

#631 [606] Password recovery endpoint: Sends user an email with a change password ticket to update password
  backend/lib/components/Auth0.js
  backend/lib/endpoints/auth.js
  backend/lib/endpoints/schema/auth.js
Labels: BACKEND, MVP - Release 1, User Auth

#700 Add Google Tag Manager environment variable
  .github/workflows/production-workflow.yml
  .github/workflows/staging-workflow.yml
Labels: DevOps, MVP - Critical

#607 Fixed the bi-directional back-button- flow from feed to onbaording
  client/src/pages/NeedHelp.js
Labels: Desktop, Difficulty - Easy, FRONTEND, Feed, MVP - Release 1, Onboarding, bug

#727 Add unique constraint to user's email at mongoose model
  backend/lib/models/User.js
  backend/package-lock.json
  backend/package.json
Labels: BACKEND, Database, Difficulty - Easy, User

#728 Cleaning up console warnings from the client (removed unused, refactored code)
  client/src/components/Button/LeftRightIconButton.js
  client/src/components/Button/SubmitButton.js
  client/src/components/CreatePost/CreatePost.js
  client/src/components/CreatePost/CustomModal.js
  client/src/components/CreatePost/Form/AskHelp.js
  client/src/components/CreatePost/Form/OfferHelp.js
  client/src/components/CreatePost/StyledModal.js
  client/src/components/Feed/FilterAccordion.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostSocial.js
  client/src/components/Header.js
  client/src/components/Input/Checkbox.js
  client/src/components/Selector/Selector.js
  client/src/components/StepWizard/WizardNav.js
  client/src/components/StepWizard/WizardSubmit.js
  client/src/hooks/reducers/organizationReducers.js
  client/src/hooks/reducers/userReducers.js
  client/src/pages/CovidScreening/GenericMessage.js
  client/src/pages/EditAccount.js
  client/src/pages/NrMap.js
  client/src/pages/OfferHelp.js
  client/src/pages/ResultsPage.js
  client/src/pages/SymptomsCheck.js
  client/src/templates/layouts/MobileTabs.js
  client/src/templates/layouts/NavigationLayout.js
Labels: Difficulty - Easy, FRONTEND, Frontend clean up

#739 Cypress e2e test general structure and folders
  .gitignore
  cypresse2e/cypress.json
  cypresse2e/cypress/integration/e2eTests/header/header.spec.js
  cypresse2e/cypress/integration/e2eTests/home/homePage.spec.js
  cypresse2e/cypress/plugins/index.js
  cypresse2e/cypress/support/commands.js
  cypresse2e/cypress/support/index.js
  cypresse2e/package.json
Labels: e2eTests

#661 Posts: Api integration -- Connect API for Post CRUD operations
  backend/lib/endpoints/posts.js
  client/src/assets/data/createPostSettings.js
  client/src/assets/data/formToPostMappings.js
  client/src/components/Button/SubMenuButton.js
  client/src/components/CreatePost/EditPost.js
  client/src/components/CreatePost/Form/EditForm.js
  client/src/components/CreatePost/Form/Form.js
  client/src/components/CreatePost/Form/TabForms.js
  client/src/components/CreatePost/Form/ThirdSection.js
  client/src/components/CreatePost/StyledPostAs.js
  client/src/components/Feed/Comments.js
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostCard.js
  client/src/components/Feed/PostSocial.js
  client/src/components/Feed/Posts.js
  client/src/components/Feed/StyledLoader.js
  client/src/components/Header.js
  client/src/components/Selector/Selector.js
  client/src/hooks/actions/feedActions.js
  client/src/hooks/reducers/feedReducers.js
  client/src/pages/Feed.js
  client/src/pages/PostPage.js
  client/src/routes.js
  client/src/templates/RouteWithSubRoutes.js
  client/src/templates/layouts/NavigationLayout.js
Labels: API Integration, BACKEND, FRONTEND, Feed, MVP - Critical, MVP - Release 1, Post

#770 Add transition to NeedHelp and OfferHelp from Home
  client/package-lock.json
  client/package.json
  client/src/components/StepWizard/StyledWizard.js
  client/src/pages/NeedHelp.js
  client/src/pages/OfferHelp.js
Labels: Desktop, FRONTEND

#774 Fix facebook logo fill to match other logos
  client/src/assets/icons/social-facebook.svg
Labels: FRONTEND

#734 Author References Synchronization
  backend/lib/endpoints/organizations.js
  backend/lib/endpoints/schema/users.js
  backend/lib/endpoints/users.js
  backend/lib/models/Comment.js
  backend/lib/models/IndividualUser.js
  backend/lib/models/OrganizationUser.js
  backend/lib/models/Post.js
Labels: BACKEND, Database, User

#788 Adding redirect back button from post to feed page
  client/src/components/Feed/Post.js
  client/src/components/StepWizard/WizardFormNav.js
  client/src/components/StepWizard/WizardNav.js
Labels: FRONTEND

#815 Feature/author filter
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/schema/posts.js
Labels: BACKEND, MVP - Critical, Post, Post Filters

#816 Fixing Back button position and visibility in Post page
  client/src/components/Feed/Post.js
  client/src/components/StepWizard/WizardFormNav.js
Labels: FRONTEND, Mobile Web

#803 Org profile ui func
  client/src/assets/data/createOrganizationProfile.js
  client/src/pages/CreateOrganizationProfile.js
Labels: MVP - Critical, Organization Profile

#826 Fix Create Post Form - expires and shareWith Dropdowns
  client/src/components/CreatePost/Form/Form.js
Labels: Desktop, FRONTEND, Feed, bug

#831 Fix showing user's post activity on profile page
  client/src/pages/Profile.js
Labels: FRONTEND, Individual Profile, MVP - Critical, MVP - Release 1

#769 Load post comments API integration
  client/src/components/CreatePost/EditPost.js
  client/src/components/CreatePost/Form/EditForm.js
  client/src/components/CreatePost/Form/TabForms.js
  client/src/components/Feed/Comments.js
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostCard.js
  client/src/components/Feed/PostSocial.js
  client/src/components/Feed/Posts.js
  client/src/hooks/actions/postActions.js
  client/src/hooks/reducers/postReducers.js
  client/src/pages/Feed.js
  client/src/pages/PostPage.js
Labels: API Integration, Comment, FRONTEND, Feed, MVP - Critical, MVP - Release 1, Post

#850 Fix for blank profile page on master branch
  client/src/components/Profile/Activity.js
Labels: FRONTEND, MVP - Critical, MVP - Release 1, bug

#849 Displaying the Organizations list in the create post modal
  backend/lib/endpoints/auth.js
  backend/lib/endpoints/users.js
  backend/lib/models/IndividualUser.js
  client/src/components/CreatePost/CreatePost.js
  client/src/pages/Feed.js
Labels: FRONTEND

#854 Fix/Proposal - Profile page create post functionality
  client/src/components/CreatePost/CreatePost.js
  client/src/pages/Profile.js
Labels: FRONTEND, bug

#808 profile-drop-down-navigation + add,list and view organisations in navigation drop down
  backend/lib/endpoints/auth.js
  client/src/components/Header.js
  client/src/pages/PrivacyPolicy.js
  client/src/templates/layouts/NavigationLayout.js
Labels: BACKEND, FRONTEND, MVP - Critical, Organization Profile

#766 created backend endpoint to submit data to SendGrid (will do FE in another PR)
  backend/.env.example_docker
  backend/.env.example_local
  backend/config.js
  backend/lib/endpoints/schema/sendgrid.js
  backend/lib/endpoints/sendgrid.js
  backend/lib/index.js
Labels: API Integration, Difficulty - Medium, In Progress, MVP - Critical

#860 Feature/add tos and privacy policy checkboxes to create user profile page
  client/src/pages/CreateUserProfile.js
Labels: Difficulty - Easy, Individual Profile, MVP - Critical

#873 add safe navigation to user?.organizations?.
  client/src/components/Header.js
Labels: bug

#884 Add Terraform Fargate task module to main repo
  main.tf
  terraform-task-module/alb-listener-rule.tf
  terraform-task-module/locals.tf
  terraform-task-module/logging.tf
  terraform-task-module/security-group.tf
  terraform-task-module/service.tf
  terraform-task-module/task-definition.tf
  terraform-task-module/variables.tf
Labels: DevOps

#885 Fix key errors and creating post from Organization page
  client/src/components/CreatePost/CreatePost.js
  client/src/components/Header.js
  client/src/pages/OrganizationProfile.js
Labels: FRONTEND, MVP - Critical, MVP - Release 1, bug

#880 added menuicon from zeplin design
  client/src/components/Header.js
Labels: bug

#881 Replaced the heading message with the correct one
  client/src/pages/Home.js
  cypresse2e/cypress/integration/e2eTests/home/homePage.spec.js
Labels: Frontend clean up

#886 Fixes mobile Organization list and desktop list styling
  client/src/components/Header.js
  client/src/templates/layouts/NavigationLayout.js
Labels: FRONTEND, MVP - Critical, MVP - Release 1, bug

#866 refetch user on org add/update
  client/src/actions/authActions.js
  client/src/pages/EditOrganizationAccount.js
  client/src/pages/OrgProfileComplete.js
Labels: FRONTEND

#862 added redirection to the main profile on save from edit account/profile
  client/src/pages/EditAccount.js
  client/src/pages/EditProfile.js
Labels: Difficulty - Easy, FRONTEND

#892 Reducing transition time from Home to NeedHelp and OfferHelp
  client/src/pages/NeedHelp.js
  client/src/pages/OfferHelp.js
Labels: Desktop, FRONTEND, Mobile, bug

#829 Reposition Post back button outside of Post border
  client/src/components/Feed/Post.js
  client/src/components/StepWizard/WizardFormNav.js
Labels: FRONTEND

#890 Add Datadog Fargate task monitoring
  main.tf
  terraform-task-module/alb-listener-rule.tf
  terraform-task-module/logging.tf
  terraform-task-module/task-definition.tf
  terraform-task-module/variables.tf
Labels: DevOps

#900 setting the number of posts for userprofile display to -1
  client/src/pages/Profile.js
Labels: Difficulty - Easy, FRONTEND, Individual Profile, MVP - Critical

#898 Add liked and likes count at GET /posts/:postId
  backend/lib/endpoints/posts.js
Labels: BACKEND, Database, MVP - Critical, MVP - Release 1

#896 Feature/integrate onboarding answers
  client/src/components/StepWizard/SkipLink.js
  client/src/hooks/reducers/feedReducers.js
  client/src/pages/Feed.js
  client/src/pages/NeedHelp.js
  client/src/pages/OfferHelp.js
Labels: Difficulty - Medium, FRONTEND, Feed, Onboarding

#889 Feature/user public profile
  backend/lib/endpoints/users.js
  client/src/components/Button/SubMenuButton.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostSocial.js
  client/src/components/Feed/Posts.js
  client/src/components/Header.js
  client/src/pages/EditAccount.js
  client/src/pages/EditProfile.js
  client/src/pages/PostPage.js
  client/src/pages/Profile.js
  client/src/pages/ProfileCompleted.js
  client/src/routes.js
  client/src/templates/layouts/NavigationLayout.js
Labels: BACKEND, Difficulty - Medium, FRONTEND, Individual Profile
