Repository FightPandemics/FightPandemics, pull requests merged in 2020-07, with the labels that each got.

#913 Integrate sendgrid on the frontend
  backend/lib/endpoints/schema/sendgrid.js
  backend/lib/endpoints/sendgrid.js
  client/src/pages/NeedHelp.js
  client/src/pages/OfferHelp.js
Labels: API Integration, Difficulty - Medium, In Progress

#859 Edit and Delete a comment in a post
  client/src/assets/data/formToPostMappings.js
  client/src/components/Feed/Comments.js
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/StyledComment.js
  client/src/hooks/actions/postActions.js
  client/src/hooks/reducers/postReducers.js
Labels: API Integration, Comment, FRONTEND, MVP - Critical, MVP - Release 1, Post

#926 Feature/only update own org
  backend/lib/endpoints/organizations.js
  backend/lib/endpoints/schema/organizations.js
  client/src/pages/CreateOrganizationProfile.js
  client/src/pages/OrganizationProfile.js
Labels: BACKEND, FRONTEND

#951 Fixed word-wrap bug
  client/src/components/Feed/PostCard.js
  client/src/components/Feed/StyledComment.js
Labels: FRONTEND, Post, bug

#955 Every post, regardless of length, has a line
  client/src/components/Feed/Post.js
Labels: FRONTEND, Feed, Post

#963 Feature/ Send button for comments in post view
  .DS_Store
  client/src/assets/icons/send.svg
  client/src/components/Input/AutoSize.js
  client/src/components/Input/TextArea.js
Labels: Comment, FRONTEND, MVP - Critical, MVP - Release 1

#958 On-hover, post page buttons match styleguide colors
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/StyledCommentButton.js
Labels: Comment, FRONTEND, Post

#964 Fixed comments age reactivity issue
  backend/lib/endpoints/posts.js
  backend/lib/models/Comment.js
  backend/lib/utils.js
  client/src/assets/data/formToPostMappings.js
  client/src/components/Feed/NestedComments.js
Labels: BACKEND, Comment, MVP - Release 1, Post, bug

#980 Resolve the issues #869 and #878
  client/src/pages/EditOrganizationAccount.js
  client/src/pages/OrganizationProfile.js
Labels: FRONTEND, MVP - Critical, MVP - Release 1, Organization Profile

#993 Add padding to heading from typography to fix sign-in overlap with FP…
  client/src/components/Typography/Heading.js
Labels: FRONTEND, Frontend clean up, bug

#989 Fixed word-wrap in mobile web
  client/src/components/Feed/Post.js
  client/src/components/Feed/StyledPostPage.js
  client/src/pages/PostPage.js
Labels: FRONTEND, bug

#996 updating home page text from recieve to request
  client/src/components/Header.js
  client/src/pages/Home.js
Labels: Frontend clean up

#922 Add Edit/Delete menu to organization posts
  backend/lib/endpoints/posts.js
  client/src/components/Button/SubMenuButton.js
  client/src/components/CreatePost/Form/EditForm.js
  client/src/components/Feed/Post.js
  client/src/components/Profile/Activity.js
  client/src/pages/Feed.js
  client/src/pages/OrganizationProfile.js
  client/src/pages/PostPage.js
Labels: BACKEND, FRONTEND, MVP - Critical, MVP - Release 1, Post

#1005 Stetting orgs and posts avatar icon to only 1 initial or 2 initials
  client/src/components/Feed/Post.js
  client/src/pages/EditAccount.js
  client/src/pages/EditOrganizationAccount.js
  client/src/pages/EditOrganizationProfile.js
  client/src/pages/EditProfile.js
  client/src/pages/OrganizationProfile.js
  client/src/pages/Profile.js
  client/src/templates/layouts/NavigationLayout.js
  client/src/utils/userInfo.js
Labels: Difficulty - Easy, FRONTEND

#1013 fix bug in getInitialsFromFullName Function
  client/src/utils/userInfo.js
Labels: bug

#969 Create organization error handling fixes
  backend/lib/endpoints/organizations.js
  client/src/pages/CreateOrganizationProfile.js
Labels: High Priority, MVP - Critical, Organization Profile, bug

#1025 reverting changes that were made on PR #813
  client/src/components/Button/BaseButton.js
  client/src/components/Button/SubmitButton.js
  client/src/components/CompletedProfile/CompletedProfile.js
  client/src/pages/Login.js
Labels: Difficulty - Easy, FRONTEND, bug

#1034 Display orgList from individual Profile page
  backend/lib/endpoints/users.js
Labels: BACKEND, FRONTEND, bug

#1056 Linkedin icon in organization profile - bug fix
  client/src/pages/EditOrganizationAccount.js
  client/src/pages/EditOrganizationProfile.js
Labels: FRONTEND, MVP - Critical, Organization Profile, bug

#1048 fix overlap in forgot pass page
  client/src/pages/Login.js
Labels: bug

#1053 When the user is not logged in and clicks on a post's comments, the user should be redirected to the post previously clicked after logging in
  client/src/components/Feed/PostSocial.js
  client/src/templates/RouteWithSubRoutes.js
Labels: Comment, Feed, bug

#1052 Display profile and org profile comment's icon and comment count correctly
  client/src/components/Feed/PostSocial.js
  client/src/components/Profile/Activity.js
  client/src/pages/PostPage.js
Labels: Individual Profile, MVP - Critical, Organization Profile, Post, bug

#975 update copy - issue #973
  client/src/components/Header.js
  client/src/pages/Faq.js
  client/src/pages/Feed.js
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/PrivacyPolicy.js
  client/src/pages/TermsConditions.js
  client/src/templates/layouts/NavigationLayout.js
Labels: FRONTEND, Frontend clean up

#974 Add icon to manifest.json
  client/public/logoIcon.svg
  client/public/manifest.json
Labels: Difficulty - Medium, MVP - Release 1, Mobile Web

#1067 Post's Page: When 'back' button is clicked, redirect user to previously visited page
  client/src/components/StepWizard/WizardFormNav.js
  client/src/pages/ProfileCompleted.js
  client/src/templates/RouteWithSubRoutes.js
Labels: FRONTEND, Feed, Post

#1068 changed 'organization' to 'organisation' everywhere
  backend/lib/endpoints/auth.js
  backend/lib/endpoints/organisations.js
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/schema/organisations.js
  backend/lib/endpoints/schema/organizations.js
  backend/lib/endpoints/schema/posts.js
  backend/lib/endpoints/users.js
  backend/lib/index.js
  backend/lib/models/IndividualUser.js
  backend/lib/models/OrganisationUser.js
  backend/lib/plugins/mongoose-connector.js
  backend/scripts/import-posts/init-sourced-by-fp-users.js
  backend/scripts/import-posts/map-airtable-data.js
  client/src/assets/data/createOrganisationProfile.js
  client/src/assets/icons/create-organisation.svg
  client/src/assets/icons/organisation.svg
  client/src/components/CreatePost/CreatePost.js
  client/src/components/CreatePost/Form/EditForm.js
  client/src/components/CreatePost/Form/Form.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/utils.js
  client/src/components/Header.js
  client/src/components/OrganisationProfile/CreateProfileComponents.js
  client/src/components/Profile/ProfileInfo.js
  client/src/context/OrganisationContext.js
  client/src/hooks/actions/organisationActions.js
  client/src/hooks/actions/organizationActions.js
  client/src/hooks/reducers/organisationReducers.js
  client/src/pages/CreateOrganisationProfile.js
  client/src/pages/CreateUserProfile.js
  client/src/pages/EditOrganisationAccount.js
  client/src/pages/EditOrganisationProfile.js
  client/src/pages/Feed.js
  client/src/pages/OrgProfileComplete.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/PostPage.js
  client/src/pages/PrivacyPolicy.js
  client/src/routes.js
  client/src/templates/layouts/NavigationLayout.js
Labels: Frontend clean up, bug, e2eTests

#965 Feature/908 supporting different screen sizes
  client/src/GlobalStyles.js
  client/src/components/AboutUs/AboutUsContainer.js
  client/src/components/Button/LeftRightIconButton.js
  client/src/components/Button/SubmitButton.js
  client/src/components/Card/DescriptionCard.js
  client/src/components/CompletedProfile/CompletedProfile.js
  client/src/components/CreatePost/Form/TabForms.js
  client/src/components/CreatePost/Form/ThirdSection.js
  client/src/components/CreatePost/StyledModal.js
  client/src/components/CreatePost/StyledPostAs.js
  client/src/components/EditProfile/EditComponents.js
  client/src/components/Faq/FaqContainer.js
  client/src/components/Feed/FiltersSidebar.js
  client/src/components/Feed/PostCard.js
  client/src/components/Feed/StyledComment.js
  client/src/components/Feed/StyledLoader.js
  client/src/components/Header.js
  client/src/components/Icon/SvgIcon.js
  client/src/components/Input/LocationInput.js
  client/src/components/Input/PasswordInput.js
  client/src/components/Logo/index.js
  client/src/components/NearestHospital/CheckSymptomsBox.js
  client/src/components/NearestHospital/HealthFacilities.js
  client/src/components/NearestHospital/LocalEmergencyNumber.js
  client/src/components/Profile/ProfileComponents.js
  client/src/components/Selector/StyledSelector.js
  client/src/components/StepWizard/AnswerButton.js
  client/src/components/StepWizard/AnswerCheckbox.js
  client/src/components/StepWizard/WizardCheckboxItem.js
  client/src/components/StepWizard/WizardSubmit.js
  client/src/components/Tag/FilterTag.js
  client/src/constants/theme.js
  client/src/pages/CreateUserProfile.js
  client/src/pages/Feed.js
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/NrMap.js
  client/src/pages/Profile.js
  client/src/pages/SymptomsCheck.js
  client/src/pages/VerifyEmail.js
  client/src/templates/layouts/NavigationLayout.js
Labels: Difficulty - Medium, FRONTEND, Frontend clean up

#1009 Feature/add id attribute
  client/src/components/Input/AutoSize.js
  client/src/constants/gtm-tags.js
  client/src/pages/Login.js
  client/src/pages/Profile.js
Labels: FRONTEND

#1070 Fix send button on tablets
  client/src/components/Input/AutoSize.js
Labels: bug

#1071 Redirect the user to step 3 after clicking on "Show me posts from anywhere" on step 2 in both offer help and need help pages
  client/src/pages/NeedHelp.js
  client/src/pages/OfferHelp.js
Labels: FRONTEND, Frontend clean up, MVP - Critical, Onboarding

#1049 Feature/offer help add id attribute
  client/src/components/StepWizard/WizardCheckboxItem.js
  client/src/constants/gtm-tags.js
  client/src/pages/OfferHelp.js
Labels: FRONTEND

#1051 On comment PATCH, display an 'edited' tag and the relative update time timestamp in the comment
  backend/lib/endpoints/posts.js
  backend/lib/models/Comment.js
  backend/lib/utils.js
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/StyledComment.js
  client/src/components/Feed/StyledPostPage.js
  client/src/hooks/reducers/postReducers.js
Labels: BACKEND, Comment, FRONTEND

#1072 add GET posts/ param to ignoreUserLocation
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/schema/posts.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/Profile.js
Labels: BACKEND, bug

#1082 Add Delete/Edit ellipses for profile posts
  client/src/pages/Profile.js
Labels: FRONTEND, MVP - Release 1, bug

#1092 Landing onboarding user to correct feed page
  client/src/pages/Feed.js
Labels: FRONTEND, Feed, HomePage, MVP - Critical, Onboarding, bug

#1093 When 'back' button is clicked, redirect user to previously visited page
  client/src/components/Button/SubMenuButton.js
  client/src/components/CreatePost/CreatePost.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostSocial.js
  client/src/components/StepWizard/WizardFormNav.js
Labels: FRONTEND, bug

#1101 Add ID attributes for elements Individual Profile and Org Profile (create, completed, profile page, post from profile)
  client/src/components/CreatePost/CreatePost.js
  client/src/components/CreatePost/Form/Form.js
  client/src/components/CreatePost/Form/TabForms.js
  client/src/components/CreatePost/StyledPostAs.js
  client/src/constants/gtm-tags.js
  client/src/pages/CreateOrganisationProfile.js
  client/src/pages/CreatePost.js
  client/src/pages/CreateUserProfile.js
  client/src/pages/NeedHelp.js
  client/src/pages/OfferHelp.js
  client/src/pages/OrgProfileComplete.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/Profile.js
  client/src/pages/ProfileCompleted.js
  client/src/routes.js
Labels: Difficulty - Medium, FRONTEND

#1103 Removing provider filter from Feed page when onboarding
  client/src/pages/Feed.js
Labels: FRONTEND, Feed, MVP - Critical, bug

#1100 Fix various GTM bugs
  client/src/components/Feed/PostSocial.js
  client/src/components/Input/Checkbox.js
  client/src/components/StepWizard/WizardCheckboxItem.js
  client/src/pages/OfferHelp.js
Labels: Frontend clean up, bug

#1111 Fix bug for check boxes not being clickable introduced by #1091
  client/src/components/Input/Checkbox.js
  client/src/components/StepWizard/WizardCheckboxItem.js
Labels: FRONTEND, bug

#1109 adding SendGrid API Key and SendGrid Contact List ID to main.tf
  backend/.env.example_docker
  backend/.env.example_local
  backend/config.js
  backend/lib/endpoints/sendgrid.js
  main.tf
Labels: API Integration, BACKEND, DevOps, Difficulty - Easy

#1117 Updated the mobile version from Feed to Help Board
  client/src/templates/layouts/MobileTabs.js
Labels: Difficulty - Easy, bug

#834 [761] Update post like.
  client/src/components/Feed/PostSocial.js
  client/src/hooks/actions/postActions.js
  client/src/hooks/reducers/postReducers.js
  client/src/pages/Feed.js
  client/src/pages/PostPage.js
Labels: FRONTEND, Feed, Post

#623 Feature/feedback ui modals.
  .gitignore
  backend/lib/endpoints/feedback.js
  client/src/assets/icons/mail.svg
  client/src/components/Alert/ErrorAlert.js
  client/src/components/Button/FeedbackModalButton.js
  client/src/components/Feedback/RadioGroup.js
  client/src/components/Feedback/RadioModal.js
  client/src/components/Feedback/RatingModal.js
  client/src/components/Feedback/StyledTextInput.js
  client/src/components/Feedback/TextFeedbackModal.js
  client/src/components/Feedback/ThanksModal.js
  client/src/components/Header.js
  client/src/components/Input/FormInput.js
  client/src/hooks/actions/feedbackActions.js
  client/src/hooks/reducers/feedbackReducers.js
  client/src/templates/layouts/NavigationLayout.js
Labels: Feedback, MVP - Critical, MVP - Release 1

#1105 Add ID attribute for elements on the Feed Page
  client/src/assets/data/filterOptions.js
  client/src/components/Feed/FilterAccordion.js
  client/src/components/Feed/FilterBox.js
  client/src/components/Feed/FiltersSidebar.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostSocial.js
  client/src/constants/gtm-tags.js
  client/src/pages/Feed.js
Labels: Difficulty - Medium, FRONTEND

#1132 fixed back button visibility when user clicked on comment icon
  client/src/components/Feed/Post.js
Labels: Frontend clean up

#1133 Feature/feedback thank you
  client/src/templates/layouts/NavigationLayout.js
Labels: Frontend clean up

#960 [486] Edit and Delete Comments - Some updates to PR #859.
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/Posts.js
  client/src/components/Profile/Activity.js
  client/src/hooks/actions/feedActions.js
  client/src/hooks/reducers/feedReducers.js
  client/src/hooks/reducers/postReducers.js
  client/src/pages/Feed.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/PostPage.js
  client/src/pages/Profile.js
Labels: FRONTEND, Feed, Post

#1114 footer links now display more organized
  client/src/components/Footnote.js
Labels: FRONTEND, Frontend clean up

#1139 Fix name overflow for org names
  client/src/components/CreatePost/StyledPostAs.js
Labels: Desktop, FRONTEND, MVP - Release 1, Mobile, Organization Profile, bug

#1150 Redirect prod subdomains to fightpandemics.com
  terraform-task-module/alb-listener-rule.tf
Labels: DevOps, MVP - Critical

#1160 Match rc/* and hotfix/* branches for review workflow
  .github/workflows/review-build-url.yml
  .github/workflows/review-workflow.yml
Labels: DevOps

#1174 removing .DS_Store from root folder and adding it to gitingore
  .DS_Store
  .gitignore
Labels: Frontend clean up

#1179 fixing filters for offer/request help on mobile (changed Feed.js)
  client/src/pages/Feed.js
Labels: FRONTEND, Soft Launch, bug

#1178 Feature/fix iphone overlay bug
  client/src/GlobalStyles.js
  client/src/components/Feed/FilterBox.js
Labels: Soft Launch

#1163 Feature/correct password change content
  client/src/constants/action-types.js
  client/src/pages/Login.js
  client/src/pages/VerifyEmail.js
  client/src/reducers/sessionReducer.js
  client/src/routes.js
  client/src/templates/RouteWithSubRoutes.js
Labels: Soft Launch

#1167 add userId in dataLayer of google tag manager
  client/src/App.js
  client/src/templates/layouts/NavigationLayout.js
Labels: FRONTEND, Metrics, Soft Launch, enhancement

#1197 add datadog and pagerduty logo to About us page
  client/src/assets/supporters-logos/datadog-logo.svg
  client/src/assets/supporters-logos/pagerduty.svg
  client/src/pages/AboutUs.js
Labels: FRONTEND, Low Priority, MVP - Release 1

#1212 Add datalayer to GTM in login
  client/src/App.js
  client/src/actions/authActions.js
  client/src/index.js
  client/src/pages/Login.js
  client/src/templates/layouts/NavigationLayout.js
Labels: Metrics, Soft Launch, bug

#1214 Fix various GTM tag bugs
  client/src/components/Feed/StyledAccordion.js
  client/src/components/Header.js
  client/src/components/StepWizard/ShowAnywhere.js
  client/src/pages/Feed.js
  client/src/pages/NeedHelp.js
  client/src/pages/OfferHelp.js
Labels: FRONTEND, Metrics, Soft Launch, bug

#1221 Fix non own-users to edit delete
  client/src/components/Feed/Post.js
Labels: FRONTEND, Post, Soft Launch, bug

#1222 Add auto close timer on Feedback thanksModal
  client/src/templates/layouts/NavigationLayout.js
Labels: Feedback, MVP - Release 1

#1229 Hotfix/dont log out privacy page
  client/src/actions/authActions.js
  client/src/components/PolicyPages/PolicyModal.js
  client/src/components/PolicyPages/PrivacyPolicyContent.js
  client/src/components/PolicyPages/TermsConditionsContent.js
  client/src/pages/CreateOrganisationProfile.js
  client/src/pages/CreateUserProfile.js
  client/src/pages/PrivacyPolicy.js
  client/src/pages/TermsConditions.js
Labels: Soft Launch

#1232 Added feedback GTM tags on Mobile web (scrappy but surely)
  client/src/components/Header.js
  client/src/constants/gtm-tags.js
  client/src/templates/layouts/NavigationLayout.js
Labels: Soft Launch

#1234 Refactor Ellipsis conditional in feed and post
  client/src/components/CreatePost/Form/EditForm.js
  client/src/components/Feed/Post.js
  client/src/pages/Feed.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/PostPage.js
Labels: Frontend clean up, Low Priority, Post

#1241 Adding meta tags to the index.html file to have a nicely formatted card when sharing links
  client/public/Offer-Help-Request-Help.png
  client/public/index.html
Labels: FRONTEND, Soft Launch

#1224 Fix Post title alignment and background
  client/src/components/Feed/PostCard.js
Labels: MVP - Release 1

#1215 Feature/fix post num comments
  backend/lib/endpoints/posts.js
  client/src/components/Feed/Post.js
Labels: BACKEND, FRONTEND, Post, bug

#1146 Create post succeed modal refetch posts even onCancel
  client/src/components/CreatePost/CreatePost.js
  client/src/pages/Feed.js
  client/src/pages/OrganisationProfile.js
  client/src/pages/Profile.js
Labels: FRONTEND, bug

#1173 Display user friendly message if post is deleted
  client/src/pages/OrgProfileComplete.js
  client/src/pages/PostPage.js
Labels: Desktop, High Priority, MVP - Release 1, Mobile Web, Post, bug

#1219 adding error to useform incase entering wrong address
  client/src/pages/CreateOrganisationProfile.js
  client/src/pages/CreateUserProfile.js
  client/src/pages/EditAccount.js
  client/src/pages/EditOrganisationAccount.js
Labels: Desktop, MVP - Release 1, Mobile, Organization Profile

#1131 Feature/post creation1002
  client/src/components/CreatePost/Form/FirstSection.js
Labels: FRONTEND, Frontend clean up

#1182 Fix post header text overlap
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostCard.js
  client/src/components/Feed/utils.js
Labels: FRONTEND, Mobile Web, bug

#1269 Update git branching model
  .github/pull_request_template.md
  .github/workflows/production-workflow.yml
  .github/workflows/review-build-url.yml
  .github/workflows/review-delete-workflow.yml
  .github/workflows/review-workflow.yml
  .github/workflows/staging-workflow.yml
  README.md
Labels: DevOps, documentation
