Repository FightPandemics/FightPandemics, pull requests merged in 2021-01, with the labels that each got.

#1862 Feature/backend tests for /api/posts/{postId} endpoint and dbHelper
  mocha/package-lock.json
  mocha/package.json
  mocha/test/feedback.test.js
  mocha/test/login.test.js
  mocha/test/organisation.test.js
  mocha/test/postId.test.js
  mocha/test/posts.test.js
  mocha/test/signup.test.js
  mocha/utils/apiHelper.js
  mocha/utils/dbHelper.js
  mocha/utils/validators.js
Labels: e2eTests

#2102 E2E fix failing tests - Cypress
  cypresse2e/cypress/elements/pages/post.js
  cypresse2e/cypress/fixtures/errorMessages.json
  cypresse2e/cypress/integration/e2eTests/footer/footer.spec.js
  cypresse2e/cypress/integration/e2eTests/post/post.spec.js
Labels: e2eTests

#2115 Add mochawesome report for backend tests & fix backend failed tests
  cypresse2e/Readme.md
  docker-compose.yml
  mocha/.gitignore
  mocha/Dockerfile
  mocha/Readme.md
  mocha/package-lock.json
  mocha/package.json
Labels: e2eTests

#2105 1672 - BUG FIX: On enter or shift + return, allow a newline to be created on comment, do not submit
  client/src/components/Input/AutoSize.js
Labels: Comment, FRONTEND, bug

#2119 API-Backend Test for Version Endpoint
  mocha/test/login.test.js
  mocha/test/signup.test.js
  mocha/test/version.test.js
  mocha/utils/apiEndpoints.js
Labels: e2eTests

#2029 Verified Badges
  backend/config.js
  backend/lib/components/Veriff.js
  backend/lib/endpoints/organisations.js
  backend/lib/endpoints/posts.js
  backend/lib/endpoints/users.js
  backend/lib/models/Author.js
  backend/lib/models/Notification.js
  backend/lib/models/Thread.js
  backend/lib/models/User.js
  backend/lib/plugins/notifier.js
  backend/lib/plugins/socket.js
  client/package-lock.json
  client/package.json
  client/src/assets/verification/arrow.svg
  client/src/assets/verification/tick.svg
  client/src/assets/verification/verify.svg
  client/src/components/Feed/NestedComments.js
  client/src/components/Feed/Post.js
  client/src/components/Feed/PostCard.js
  client/src/components/Feed/StyledComment.js
  client/src/components/Feed/User.js
  client/src/components/Inbox/ChatList.js
  client/src/components/Inbox/RecipientHeader.js
  client/src/components/Notifications/NotificationDropDown.js
  client/src/components/Selector/Selector.js
  client/src/components/Verification/Banner.js
  client/src/components/Verification/StepModal.js
  client/src/components/Verification/StyledBanner.js
  client/src/components/Verification/StyledModal.js
  client/src/components/Verification/Tick.js
  client/src/components/Verification/index.js
  client/src/components/Verification/steps.js
  client/src/locales/translations/en_US.json
  client/src/pages/OrganisationProfile.js
  client/src/pages/Profile.js
  main.tf
Labels: p_verifiedBadges

#2152 Add ID to Book Call Button on About Us Page
  client/src/constants/gtm-tags.js
  client/src/pages/AboutUs.js
Labels: FRONTEND, e2eTests

#2151 Added additional test for the About Us page Book a Call section
  cypresse2e/cypress/elements/pages/aboutUs.js
  cypresse2e/cypress/integration/e2eTests/aboutUs/aboutUs.spec.js
  cypresse2e/cypress/support/commands.js
Labels: FRONTEND, e2eTests
